class InspeccionGD: Codable {
    var CodInspeccion = ""
    var CodTipo = ""
    var CodContrata = ""
    var FechaP = ""
    var Fecha = ""
    var Gerencia = ""
    var SuperInt = ""
    var CodUbicacion = ""
    var CodSubUbicacion = ""
    var EquipoInspeccion = ""
    var PersonasAtendidas = ""
    var Elemperpage = ""
    var Pagenumber = ""
    var Estado = ""
}
