class PlanAccionDetalle {
    var CodAccion = ""
    var NroDocReferencia = ""
    var CodTipoObs = ""
    var CodSolicitadoPor = ""
    var SolicitadoPor = ""
    var CodActiRelacionada = ""
    var CodEstadoAccion = ""
    var CodNivelRiesgo = ""
    var CodAreaHSEC = ""
    var CodReferencia = ""
    var CodTipoAccion = ""
    var FecComprometidaInicial = ""
    var FecComprometidaFinal = ""
    var DesPlanAccion = ""
    var CodResponsables = ""
    var Responsables = ""
    var CodTabla = ""
    var NroAccionOrigen = "" // 1
    var FechaSolicitud = ""
    var Estado = ""
}
